services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: crud_mysql_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase

volumes:
  mysql_data: